config/routes.rb
Rails.application.routes.draw do
  resources :months, only: [:show, :home] do
    resources :tasks
  end
  get 'months/:id/prev' => 'months#prev_month', as: :prev_month
  get '/months/:id/next' => 'months#next_month', as: :next_month
  get '/months/:month_id/day/:day/more' => 'tasks#more', as: :more_task_day
  get '/upcoming' => 'tasks#upcoming', as: :upcoming
  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }
  root "months#home"
  get '/overdue' => 'tasks#old_news', as: :overdue
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :calendar, optional: false
  belongs_to :month, optional: false
  validates :content, presence: true
  validates :start_time, presence: true
  validate :time_cannot_be_in_the_past

  def time_cannot_be_in_the_past
    if !start_time.blank? and start_time < (Time.now - 4.hour)
      errors.add(:start_time, "can't be in the past")
    end
  end

  
  def date=(date)
    if date.values[0].length > 0
      t = format_date(date.values)
      time = Time.new(t[0],t[1],t[2],t[3],t[4])
      self.month = self.calendar.find_month_by_time(time)
      self.start_time = time
    end
  end
  
  def format_date(date)
    result = date[0].split('T').join('-').split('-')
    result[3] = result[3].split(':')
    result.flatten.map(&:to_i)
  end

  def self.upcoming_for_user(user)
    tasks = joins(:calendar).where(["calendar_id = ?", user.calendar.id]).where('start_time >= ?', Time.now - 4.hour).order("start_time")
  end
  
  def self.past_task(user)
    tasks = joins(:calendar).where(["calendar_id = ?", user.calendar.id]).where('start_time < ?', Time.now - 4.hour).order("start_time")
  end

  def time
    start_time.strftime("%b %e, %l:%M %p")
  end
  
  def month_time
    start_time.strftime('%m %M %p')
  end
  
  def day 
    start_time.day
  end

  def link
    "/months/#{self.month.id}/tasks/#{self.id}"
  end
  
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def new
    if !Month.exists?(params[:month_id])
      redirect_to '/', alert: "Month not found."
    else
      @month = my_cal.months.find_by(id: params[:month_id])
      @task = Task.new(month_id: params[:month_id])
    end
  end

  def edit
    @month = my_cal.months.find_by(id: params[:month_id])
    if @month.nil?
      redirect_to '/', alert: "Month not found."
    else
      @task = @month.tasks.find_by(id: params[:id])
      redirect_to '/', alert: "Task not found." if @task.nil?
    end
  end

  def create
    @task = Task.new(task_params)
    respond_to do |format|
      if @task.save
        my_cal.save
        @month = @task.month
        format.html { redirect_to @month}
        format.json { render json: @month}
      else
        @month =  my_cal.months.find_by(id: params[:month_id])
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  def more
    if !Month.exists?(params[:month_id])
      redirect_to '/', alert: "Month not found."
    else
      @month = my_cal.months.find_by(id: params[:month_id])
      @tasks = @month.tasks_today(params[:day])
      redirect_to @month, alert: "Task not found." if @tasks.empty?
    end
    render :show
    # respond_to do |format|
    #   format.html { render :index}
    #   format.json { render json: @tasks}
    # end
  end

  def show
    if !Month.exists?(params[:month_id])
      redirect_to '/', alert: "Month not found."
    else
      @month = my_cal.months.find_by(id: params[:month_id])
      @task =  @month.tasks.find_by(id: params[:id])
      redirect_to '/', alert: "Task not found." if @task.nil?
    end
    respond_to do |format|
      format.html { render :show}
      format.json { render json: @task}
    end
  end

  def update
    @task = Task.find(params[:id])
    if @task.update(task_params)
      @month = @task.month
      redirect_to @month
    else
      @month =  my_cal.months.find_by(id: params[:month_id])
      render :edit
    end
  end

  def destroy
    task = current_user.tasks.find_by(id: params[:id])
    if task
      month = task.month
      task.destroy
      redirect_to month, alert: "Task deleted."
    else
      redirect_to '/', alert: "Task not found."
    end
  end

  def index
    @month = my_cal.months.find_by(id: params[:month_id])
    months = my_cal.months.select { |e| !e.tasks.empty?  }
    @tasks = months.map(&:tasks).flatten
    respond_to do |format|
      format.html { render :index}
      format.json { render json: @tasks}
    end
  end

  def upcoming
    @tasks = my_cal.upcoming_tasks
    @month = my_cal.find_month_by_time(Time.now)
    respond_to do |format|
      format.html { render :index}
      format.json { render json: @tasks}
    end
  end

  def old_news
    @tasks = my_cal.old_news
    @month = my_cal.find_month_by_time(Time.now)
    respond_to do |format|
      format.html { render :index}
      format.json { render json: @tasks}
    end
  end

  private
    def task_params
      a = params.require(:task).permit(:content, :calendar_id).to_hash
      b = {date: params.require(:date).permit([:year, :month, :day, :hour, :minute]).to_hash}
      return a.merge(b)
    end
end

app/helpers/tasks_helper.rb
module TasksHelper

  def task_index_header(tasks)
    task= tasks[0]
    content_tag(:b, "#{task.month.name} #{task.month.year}")
  end
  
  def task_display(tasks)
   task = tasks[0]
   link_to(month_task_path(task.month, task)) do
     content_tag :div, class: 'event' do
       content_tag(:div, "#{task.content}", class:'event-desc') +
       content_tag(:div, "#{task.time}" ,class: 'event-time')
     end
   end
 end

 def task_filter(month, day)
   tasks = month.tasks.select{|e| e.start_time.day == day }
   tasks.select {|task| current_user.tasks.include?(task)}
 end
 
 def show_task(month, day)
  tasks = task_filter(month, day)
  task_display(tasks) if tasks.length > 0
 end
end

app/views/tasks/_form.html.erb
<% if task.errors.any? %>
  <div id="error_explanation">
    <h3>
      <%= pluralize(task.errors.count, "error") %>
      prohibited this product from being saved:
    </h3>

   <ul>
    <% task.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= f.label :content %></br>
<div class="field <%= 'field_with_errors' if task.errors[:content].any? %>">
  <%= f.text_field :content %></br>
</div>

<%= f.hidden_field :calendar_id, value: my_cal.id %>
<%= f.label 'Time' %></br>

<div class="field <%= 'field_with_errors' if task.errors[:start_time].any? %>" id='time' >
  <input type="datetime-local" name="date[hour]" id="date_hour" value="{{ this }}"/>
</div>
<%= content_tag :div, class: 'actions' do %>
<%= f.submit %></br>
<% end %>

app/views/tasks/_show_tasks.html.erb
<div class="task-page">
  <% tasks.each do |task| %>
    <div class="task-show">
      <p><%= "#{task.start_time.strftime('%b %e, %l:%M %p')}" %></p>
      <p id='task-content'><%= "#{task.content}" %></p>
      <%= link_to 'Edit', edit_month_task_url(month, task), id: 'edit' %>
      <div id = 'delete'><%= link_to 'Delete', month_task_path(month, task), method: :delete, data: { confirm: 'Are you sure?' } %></div>
    </div>
  <% end %>
</div>

app/views/tasks/_template.html.erb
<script id="tasks-index-template" type="text/x-handlebars-template">
    <div class='row'>
      {{#each this}}
         <div class="task-show">
          <p>{{ time }}</p>
          <p id='task-content'>{{content}}</p>
          <%= link_to 'Edit',  '/months/{{ month.id }}/tasks/{{ id }}/edit', id: 'edit' %>
          <div id = 'delete'><%= link_to 'Delete', '/months/{{ month.id }}/tasks/{{ id }}', method: :delete, data: { confirm: 'Are you sure?' } %></div>
        </div>
      {{/each}}
    </div>
</script>

app/views/tasks/edit.html.erb
<header>
    <h1>Edit Task</h1>
</header>
<div class="forms">
  <%= form_for(@task, url: month_task_path(@month, @task)) do |f| %>
    <%= render partial: 'tasks/form', locals: {month: @month, task: @task, f: f} %>
  <%end%>
</div>

app/views/tasks/index.html.erb
<body class="task-index-page">
  <header>
    <h1>Tasks</h1>
  </header>
  <div id="anchor-tasks"></div>

<%= render partial: 'tasks/template' %>
</body>

app/views/tasks/new.html.erb
<header>
    <h1>Create Task</h1>
</header>

<div class="forms">
  <%= form_for(@task, url: month_tasks_path(@month)) do |f| %>
    <%= render partial: 'tasks/form', locals: {month: @month, task: @task, f: f} %>
  <%end%>
</div>

app/views/tasks/show.html.erb
<header>
  <h1><%= "#{@month.name} #{@task.start_time.day} #{@month.year}" %> </h1>
</header>

<div class="task-show">
  <p><%= "#{@task.start_time.strftime('%b %e, %l:%M %p')}" %></p>
  <p id='task-content'><%= "#{@task.content}" %></p>
  <%= link_to 'Edit', edit_month_task_url(@month, @task), id: 'edit' %>
  <div id = 'delete'><%= link_to 'Delete', month_task_path(@month, @task), method: :delete, data: { confirm: 'Are you sure?' } %></div>
</div>