config/routes.rb
Rails.application.routes.draw do
  resources :months, only: [:show, :home] do
    resources :tasks
  end
  get 'months/:id/prev' => 'months#prev_month', as: :prev_month
  get '/months/:id/next' => 'months#next_month', as: :next_month
  get '/months/:month_id/day/:day/more' => 'tasks#more', as: :more_task_day
  get '/upcoming' => 'tasks#upcoming', as: :upcoming
  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }
  root "months#home"
  get '/overdue' => 'tasks#old_news', as: :overdue
end

app/views/layouts/_header.html.erb
<div id="mytopnav">
  <nav >
    <ul>
      <% if logged_in? %>
        <li style="float:left"><%= link_to 'Last Month', prev_month_path(@month), class: "js-next", id: 'prev'%></li>
        <li class='dropdown'>
          <a href="javascript:void(0)" class="dropbtn"><%= current_user.username %></a>
          <div class="dropdown-content">
            <%= link_to 'Sign out', destroy_user_session_path, method: :delete %>
          </div>
        </li>
        <li class='dropdown'>
          <div class="dropbtn"><%= link_to 'Today', '/' %></div>
          <div class="dropdown-content">
            <%= link_to 'All Tasks', month_tasks_path(@month), id: 'alltasks' %>
            <%= link_to 'Upcoming', upcoming_path, class: 'get-tasks' %>
            <%= link_to 'Overdue', overdue_path, class: 'get-tasks' %>
          </div>
        </li>
        <li style"float:right"><%= link_to 'New Task', new_month_task_path(@month), id: 'new-task-link' %></li>
        <li style="float:right"><%= link_to 'Next Month', next_month_path(@month), class: "js-next", id: 'next' %></li>
      <%else%>
        <li><%= link_to "Sign in", new_user_session_path %></li>
        <li><%= link_to "Sign up", new_user_registration_path %></li>
      <% end %>
    </ul>
  </nav>
</div>

app/views/layouts/_messages.html.erb
<%= content_tag(:div, flash[:error], :id => "flash_error") if flash[:error] %>
<%= content_tag(:div, flash[:notice], :id => "flash_notice") if flash[:notice] %>
<%= content_tag(:div, flash[:alert], :id => "flash_alert") if flash[:alert] %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyCal</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= render 'layouts/messages'%>
    <%= yield %>
  </body>
</html>